### PR TITLE
Fix null body response to empty in ApiClient

### PR DESCRIPTION
**Pull request by tanmay-db**
## Changes

Some delete end points return null instead of empty body, we fix that in SDK Client since the APIs are not available publicly and support isn't available for them yet. 

## Tests

Thanks to @sodle-splunk for contributing the unit test (https://github.com/databricks/databricks-sdk-py/pull/641)
- [x] `make test` run locally
- [x] `make fmt` applied
- [ ] relevant integration tests applied

### CODE REVIEW

**Review by mgyucht — COMMENTED** [review]
Test?

**Comment by tanmay-db** [comment]
> Test?

@mgyucht, I have asked on slack for confirmation on the fix, since the API is private, we might need to enable it for our test infra and then repro this, it would be some work, once confirmed I will add unit test. Me and @edwardfeng-db are working on other issues in the meantime parallelly.

**Comment by tanmay-db** [comment]
Note: The failing test: `downstreams / compatibility (blueprint, databrickslabs) (pull_request)` fails on a simple text change: https://github.com/databricks/databricks-sdk-py/pull/643. This passed on last commit which was 2 weeks ago and doesn't seem to be happening due to changes in Python SDK.

**Comment by nkvuong** [comment]
the failed check is not related to this change, the same test is failing on blueprint/main

**Review by sodle-splunk — APPROVED** [review]
Thanks all for quick response and feedback on this one. This bug is one of our final blockers to shipping a new integration. 🥳

**Comment by tanmay-db** [comment]
Hi @sodle-splunk, thanks for raising this, the release with fix has been done: https://github.com/databricks/databricks-sdk-py/releases/tag/v0.27.1

**Pull request merged**
